[Python 완전정복 시리즈] 2편 : Pandas DataFrame 완전정복 -19. 형식변환
■ csv으로 변환 (to_csv)
DataFrame.to_csv(path_or_buf=None, sep=',', na_rep='', float_format=None, columns=None, header=True, index=True, index_label=None, mode='w', encoding=None, compression='infer', quoting=None, quotechar='"', line_terminator=None, chunksize=None, date_format=None, doublequote=True, escapechar=None, decimal='.', errors='strict', storage_options=None)

to_csv 메서드는 데이터프레임 객체를 csv 형식으로 변환하는 메서드입니다.

- df.to_csv(path_or_buf=None, sep=',', na_rep='', float_format=None, columns=None, header=True, index=True, index_label=None, mode='w', encoding=None, compression='infer', quoting=None, quotechar='"', line_terminator=None, chunksize=None, date_format=None, doublequote=True, escapechar=None, decimal='.', errors='strict', storage_options=None)
path_or_buf : csv파일이 생성되는 경로와 파일명 입니다.
sep : csv 파일의 구분자 입니다. 기본값은 ' , ' 입니다.
na_rep : 결측값을 어떻게 출력할지 지정할 수 있습니다. 기본값은 공백 입니다.
float_format : 부동소수점의 경우 어떤 형식으로 출력할지 지정할 수 있습니다.
columns : 출력할 열을 지정하는 인수 입니다.
header : 열 이름을 설정합니다. False일 경우 열 이름을 출력하지 않습니다.
index : 인덱스의 출력 여부 입니다. False일 경우 인덱스를 출력하지 않습니다.
index_label : 인덱스의 레이블(인덱스명)을 설정합니다.
mode : {'w' / 'a'} 쓰기 모드를 지정합니다. a로 지정할 경우 기존 파일 아래에 값을 추가하여 입력하게됩니다.
encoding : 인코딩 설정입니다. 기본값은 utf-8입니다.
compression : {‘infer’, ‘gzip’, ‘bz2’, ‘zip’, ‘xz’, None} 압축 설정을 지정합니다. 기본값은 'infer'로 적절한 압축형식을 추론합니다.
quoting : 값에 대해서 인용구 설정을 할 수 있습니다. 어떤 값에 대해서 인용구를 설정할지는 아래와 같습니다.
{0 : MINIMAL 문자와 특수문자 / 1 : ALL 모든필드 / 2 : NONNUMERIC 숫자가 아닌것 / 3 : NONE 안함}
quotechar : quoting에서 지정한 인용구에 대해서 인용구에 사용할 문자를 지정합니다. 기본값은 쌍따옴표 입니다.
line_terminator : 
chunksize : 한번에 불러올 행의 수를 지정합니다. 예를들어 100을 입력할 경우 한번에 100행씩 변환합니다. 속도 향상에 기여합니다.
date_format : 값이 시계열(datetime) 데이터인 경우 그 값의 포맷을 지정합니다.(예 : '%Y-%m')
doublequoto : 값중에 quotechar과 같은 값이 있을때, 그 값을 인용구 처리할지의 여부 입니다.
escapechar : doublequoto=False인 경우 인용구와 중복되는 그 값을 어떤 값으로 변경할지 여부입니다.
decimal : 자리수로 쓰이는 문자를 지정합니다.즉, 100,000의 경우 decimal="."으로 할 경우100.000으로 표시합니다.
errors : 인코딩 오류에 대해서 오류 처리를 정할 수 있습니다. 가능한 값은 아래와 같습니다.
{strict : 인코딩 오류에 ValueError 발생 / ignore : 무시 / replace 잘못된 데이터를 대체마커 '?' 지정 / ...}
더 많은 값에 대해서는 python library 의 strict 문서 참고 바랍니다.
storage_options : 특정 스토리지 연결에 적합한 추가 옵션, 예: 호스트, 포트, 사용자 이름, 비밀번호 등을 지정합니다.

In [2]:
#import sys !{sys.executable} -m pip install tabulate

import numba
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
import openpyxl
import tabulate

In [28]:
data = [[1,np.nan],['A',4.1],['-','3']]
df = pd.DataFrame(data)
address = 'D:\\생성 AI 응용 서비스 개발자 양성 과정\\AI STUDY\\github\\pandas\\' #기본 경로 설정해줌(코딩이 길어지므로)
print(df)
df.to_csv(path_or_buf=address+'test1.csv')
df.to_csv(path_or_buf=address+'test2.csv', sep='-')
df.to_csv(path_or_buf=address+'test3.csv', na_rep=100)
df.to_csv(path_or_buf=address+'test4.csv', float_format='%.2f')
df.to_csv(path_or_buf=address+'test5.csv', columns=[0])
df.to_csv(path_or_buf=address+'test6.csv', header=['col1','col2'])
df.to_csv(path_or_buf=address+'test7.csv', index=False) 
df.to_csv(path_or_buf=address+'test8.csv', index_label=['index'])
df.to_csv(path_or_buf=address+'test9.csv', mode='w') #기존 데이터 csv파일생성
df2 = pd.DataFrame(data=[[7,8],[9,10]],index=[3,4]) # 추가 입력할 새 데이터 객체 생성
df2.to_csv(path_or_buf=address+'test9.csv', mode='a') # mode=a로 기존데이터 아래에 추가함
df.to_csv(path_or_buf=address+'test10.csv', mode='w')
df2.to_csv(path_or_buf=address+'test10.csv', mode='a',header=False)
df.to_csv(path_or_buf=address+'test11.csv',quoting=2) # 숫자가 아닌 경우 인용구 처리
df.to_csv(path_or_buf=address+'test12.csv',quoting=2,quotechar="-")
#doublequoto / escapechar인수의 사용
#df의 3행1열의 값은 하이픈(-)으로 만약 quotechar을 하이픈(-)으로 한다면 인용구 문자를 인용구 처리하는 경우가 생깁니다.
#이 경우 doublequoto=True 인 경우 그냥 무시하고 인용구 처리를 하게 되며, doublequoto=False인 경우 quotechar으로 지정되어 중복되는 값을 다른 문자로 대체합니다.
#이 경우 escapechar인수를 통해 대체할 문자의 지정이 가능합니다
df.to_csv(path_or_buf=address+'test13.csv',
          quoting=2,quotechar="-",doublequote=False,escapechar="$")

   0    1
0  1  NaN
1  A  4.1
2  -    3

■ excel로 변환 (to_excel)
* DataFrame.to_excel(excel_writer, sheet_name='Sheet1', na_rep='', float_format=None, columns=None, header=True, index=True, index_label=None, startrow=0, startcol=0, engine=None, merge_cells=True, encoding=None, inf_rep='inf', verbose=True, freeze_panes=None, storage_options=None)

to_excel 메서드는 데이터프레임 객체를 엑셀 형태로 변환하는 메서드입니다.

- df.to_excel(excel_writer, sheet_name='Sheet1', na_rep='', float_format=None, columns=None, header=True, index=True, index_label=None, startrow=0, startcol=0, engine=None, merge_cells=True, encoding=None, inf_rep='inf', verbose=True, freeze_panes=None, storage_options=None)

excel_writer : 경로와 파일 이름을 설정하거나 ExcelWriter 객체를 지정합니다.
sheet_name : 시트 이름을 설정해줍니다. 중복인 경우 덮어씌워집니다.
na_rep : 결측치를 대체할 값을 설정합니다. 기본값은 공백(" ") 입니다.
float_format : 부동소수점의 표현방식을 지정합니다.
columns : 엑셀로 변환할 열을 지정합니다.
header : 열 이름을 설정합니다. None인 경우에는 열이름을 출력하지 않습니다.
index : index의 출력 여부를 정합니다.
index_label : index명을 지정합니다. Multi Index의 경우 리스트 형식으로 지정해주어야합니다.
startrow / startcol : 값이 입력되는 위치를 지정합니다.
engine : 사용할 엔진을 지정합니다. 'openpyxl' 또는 'xlsxwriter'. io.excel.xlsx.writer, io.excel.xls.writer 및 io.excel.xlsm.writer 옵션을 통해 이를 설정할 수도 있습니다. merge_cells : Index가 중복인 경우 엑셀로 변환시 병합할지 정합니다. 기본값은 True로 병합이 됩니다.
encoding : 결과 엑셀파일의 인코딩을 지정합니다. xlwt에만 필요하며 다른 경우는 기본 유니코드를 지원합니다.
inf_rep : 엑셀은 기본적으로 무한에대한 표시형식이 없기때문에, 무한인 값을 어떻게 표시할지 정합니다. 기본값은 'inf' 입니다.
vervose : 오류 로그에 추가 정보를 표시할지 여부입니다. 기본값은 True입니다.
freeze_panes : 틀고정을 지정합니다. 튜플로 (값, 값) 형태로 지정합니다.
storage_options : 특정 스토리지 연결에 적합한 추가 옵션을 지정합니다. (예 : 호스트, 포트, 사용자 이름, 비밀번호 등)

In [42]:
data1 = [[1,np.nan],['A',4.1],[math.inf,'3']]
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data=[[5,6],[7,8],[9,10]],index=[['A','B','B'],[3,4,5]]) #멀티인덱스 객체
print(df1)
print(df2)
address = 'D:\\생성 AI 응용 서비스 개발자 양성 과정\\AI STUDY\\github\\pandas\\' #기본 경로 설정해줌(코딩이 길어지므로)
df1.to_excel(excel_writer=address+'test1-1.xlsx')
df1.to_excel(excel_writer=address+'test2-1.xlsx',sheet_name='test_sheet')
with pd.ExcelWriter(address+'test3-1.xlsx') as writer:
    df1.to_excel(writer, sheet_name='test_sheet_1')
    df2.to_excel(writer, sheet_name='test_sheet_2')
df1.to_excel(excel_writer=address+'test4-1.xlsx',na_rep='BLANK')
df1.to_excel(excel_writer=address+'test6-1.xlsx',columns=[0])
df1.to_excel(excel_writer=address+'test7-1.xlsx',header=['col1','col2'])
df1.to_excel(excel_writer=address+'test8-1.xlsx', index=False)
df2.to_excel(excel_writer=address+'test9-1.xlsx', index_label=['idx1','idx2'])
df1.to_excel(excel_writer=address+'test10-1.xlsx', startrow=2,startcol=4)
df2.to_excel(excel_writer=address+'test11_1.xlsx')
df2.to_excel(excel_writer=address+'test11_2.xlsx', merge_cells=False)
df1.to_excel(excel_writer=address+'test12-1.xlsx', inf_rep='∞')
df1.to_excel(excel_writer=address+'test13-1.xlsx', freeze_panes=(1,1))

     0    1
0    1  NaN
1    A  4.1
2  inf    3
     0   1
A 3  5   6
B 4  7   8
  5  9  10

■ 클립보드에 저장 (to_clipboard)
* DataFrame.to_clipboard(excel=True, sep=None, kwargs)
to_clipboard 메서드는 데이터를 클립보드에 저장하도록 하는 메서드입니다.

-df.to_clipboard(excel=True, sep=None, kwargs)
excel : 엑셀에 붙여넣기 하기 쉽도록 데이터를 csv형태로 클립보드에 저장할지 여부입니다.
sep : csv형태로 클립보드에 저장 할때 구분자를 지정합니다.
kwargs : csv형태로 클립보드에 저장하기때문에, kwargs에 to_csv에서 사용하는 인수를 그대로 사용할 수 있습니다.


■ dict로 변환 (to_dict)
* DataFrame.to_dict(orient='dict', into=)
to_dict 메서드는 데이터프레임 객체를 dict 형태로 변환하는 메서드 입니다.

- df.to_dict(orient='dict', into=)
orient : 출력할 dict의 형태를 지정합니다. 형태는 아래와 같습니다.

    dict : {열 : {행 : 값, 행 : 값}, 열 : {행 : 값, 행 : 값}}
    list : {열 : [ 값 ], 열 : [ 값 ] }
    series : {열 : Series, 열 : Series}
    split : { index : [ 행, 행 ], columns : [ 열, 열 ], data : [ 값, 값 ] }
    records : [ { 열 : 값 , 열 : 값 }, { 열 : 값, 열 : 값 } ]
    index : { 행 : {열 : 값, 열 : 값}, 행 : {열 : 값, 열 : 값} }

- into : 반환값의 모든 매핑에 사용되는 collections.abc.Mapping 하위클래스입니다.

■ Markdown으로 변환 (to_markdown)
*DataFrame.to_markdown(buf=None, mode='wt', index=True, storage_options=None, kwargs)
to_markdown은 DataFrame 객체를 마크다운 형식으로 변환해주는 메서드입니다.
- df.to_markdown(buf=None, mode='wt', index=True, storage_options=None, kwargs)
buf : 쓸 버퍼입니다. 입력하지 않으면 문자열이 반환됩니다.
mode : 파일을 열때 모드입니다. 기본값은 'wt'입니다.
index : 인덱스를 출력할지 여부입니다. 기본값은 True입니다.
storage_options : 특정 스토리지 연결에 적합한 추가 옵션을 지정합니다. (예 : 호스트, 포트, 사용자 이름, 비밀번호 등)
kwargs : 추가 적용 가능한 tabulate의 키워드입니다.

■ pickle객체로변환 (to_pickle)  -->❌ 1. Python 전용 파일 : Excel이나 다른 프로그램에서 열 수 없음.
* DataFrame.to_pickle(path, compression='infer', protocol=5, storage_options=None)
to_pickle메서드는 데이터객체를 Pickle 형식으로 변환해주는 메서드입니다.

- df.to_pickle(path, compression='infer', protocol=5, storage_options=None)
path : pickle 오브젝트가 저장될 경로 입니다.
compression : 출력 파일에서 사용할 압축을 나타내는 문자열입니다. 기본적으로 지정된 경로의 파일 확장자에서 추론합니다.
protocol : pickler가 사용해야 하는 프로토콜을 나타내는 Int로 기본값은 HIGHEST_PROTOCOL입니다.
자세한것은 pickle 라이브러리 12.1.2를 참고 바랍니다.
storage_options : 특정 스토리지 연결에 적합한 추가 옵션을 지정합니다.(예 : 호스트, 포트, 사용자 이름, 암호 등.)

언제 쓰는 것이 좋은가?

✔ Python 분석 환경 내부에서만 사용할 때
✔ 대용량 데이터 임시 저장
✔ 머신러닝 모델 저장
✔ dtype 유지가 중요한 경우

In [64]:
df = pd.DataFrame([[1,np.nan],['A',4.1],[math.inf,'3']])
print(df)
df.to_clipboard()
df.to_clipboard(excel=False)
df.to_clipboard(sep='-')
df.to_clipboard(header=['col1','col2'])

df = pd.DataFrame([[1,2],[3,4]], columns=['col1','col2'],index=['row1','row2'])
print(df)
#orient 인수를 설정함으로써 출력되는 dict객체의 형태를 정할 수 있습니다.
#orient = 'dict'인 경우 {열 : {행 : 값, 행 : 값}, 열 : {행 : 값, 행 : 값} 형태로 변환합니다.
print("**dict**:", df.to_dict(orient='dict'))
print("**list**:", df.to_dict(orient='list'))
print("**series**:", df.to_dict(orient='series'))
print("**split**:", df.to_dict(orient='split'))
print("**records**:", df.to_dict(orient='records'))
print("**index**:", df.to_dict(orient='index'))

df = pd.DataFrame([[1,2],[3,4]], columns=['col1','col2'],index=['row1','row2'])
print(df)
print(df.to_markdown())
print(df.to_markdown(index=False))
print(df.to_markdown(tablefmt='fancy_grid'))
address = 'D:\\생성 AI 응용 서비스 개발자 양성 과정\\AI STUDY\\github\\pandas\\' #기본 경로 설정해줌(코딩이 길어지므로)
df.to_pickle(address+'test1.pkl')
df2 = pd.read_pickle(address+'test1.pkl') #불러오기
print(df2)

     0    1
0    1  NaN
1    A  4.1
2  inf    3
      col1  col2
row1     1     2
row2     3     4
**dict**: {'col1': {'row1': 1, 'row2': 3}, 'col2': {'row1': 2, 'row2': 4}}
**list**: {'col1': [1, 3], 'col2': [2, 4]}
**series**: {'col1': row1    1
row2    3
Name: col1, dtype: int64, 'col2': row1    2
row2    4
Name: col2, dtype: int64}
**split**: {'index': ['row1', 'row2'], 'columns': ['col1', 'col2'], 'data': [[1, 2], [3, 4]]}
**records**: [{'col1': 1, 'col2': 2}, {'col1': 3, 'col2': 4}]
**index**: {'row1': {'col1': 1, 'col2': 2}, 'row2': {'col1': 3, 'col2': 4}}
      col1  col2
row1     1     2
row2     3     4
|      |   col1 |   col2 |
|:-----|-------:|-------:|
| row1 |      1 |      2 |
| row2 |      3 |      4 |
|   col1 |   col2 |
|-------:|-------:|
|      1 |      2 |
|      3 |      4 |
╒══════╤════════╤════════╕
│      │   col1 │   col2 │
╞══════╪════════╪════════╡
│ row1 │      1 │      2 │
├──────┼────────┼────────┤
│ row2 │      3 │      4 │
╘══════╧════════╧════════╛
      col1  col2
row1     1     2
row2     3     4

■  html으로 변환(to_html)
* DataFrame.to_html(buf=None, columns=None, col_space=None, header=True, index=True, na_rep='NaN', formatters=None, float_format=None, sparsify=None, index_names=True, justify=None, max_rows=None, max_cols=None, show_dimensions=False, decimal='.', bold_rows=True, classes=None, escape=True, notebook=False, border=None, table_id=None, render_links=False, encoding=None)

to_html메서드는 데이터프레임 객체를 html 문법으로 변환하는 메서드 입니다.

-df.(buf=None, columns=None, col_space=None, header=True, index=True, na_rep='NaN', formatters=None, float_format=None, sparsify=None, index_names=True, justify=None, max_rows=None, max_cols=None, show_dimensions=False, decimal='.', bold_rows=True, classes=None, escape=True, notebook=False, border=None, table_id=None, render_links=False, encoding=None)
buf : 저장할 버퍼 입니다. None이면 문자열로 출력됩니다.
columns : 출력할 열을 지정합니다.
col_space : 열 너비를 지정합니다. 픽셀 단위 입니다.
header / index : 열/행 레이블의 출력 여부 입니다. False이면 출력하지 않습니다.
na_rep : 결측값의 표현 방식 입니다.
formatters : 포매터 함수를 통해 값의 포맷을 설정합니다. .format() 메서드도 사용 가능합니다.
float_format : 소수점 단위 자리수를 지정합니다. 기본은 마침표( . ) 입니다. sparsify : 각 행의 모든 다중 인덱스 키를 인쇄하려면 계층적 인덱스가 있는 DataFrame에 대해 False로 설정합니다.
index_names : 인덱스명을 출력할지를 정합니다.
justify : 정렬 방식을 지정합니다. {left / right / center / justify / justify-all / start / end / inherit / match-parent / initial / unset}
maxrows : 최대 출력할 줄 수를 지정합니다. 초과되는 줄은 ( ... )형태로 축약됩니다.
maxcols : 최대 출력할 열 수를 지정합니다. 초과되는 줄은 ( ... )형태로 축약됩니다.
minrow : maxrows로인해 잘린 표현을 표시할 수 입니다.
show_dimensions : 출력된 html 객체 아래에 데이터 객체의 차원을 출력합니다.
decimal : 1000단위 구분기호로 인식되는 문자를 지정합니다.
bold_rows : 출력에서 행 레이블을 굵게할지 여부입니다. 기본은 True입니다.
classes 결과 html의 table에 적용할 css 클래스를 지정합니다.
escape : 문자 <, > 및 &를 HTML 안전 시퀀스로 변환합니다. 즉 문자를 HTML 문법이 아닌 문자 그대로 출력합니다.
notebook : 생성된 HTML이 IPython Notebook용인지 여부입니다. 기본은 False입니다.
border : 테두리의 두께를 지정합니다.
encoding : 인코딩을 지정합니다.
table_id : css의 table id를 설정합니다.
render_links : url을 html 링크로 변환합니다

In [88]:
address = 'D:\\생성 AI 응용 서비스 개발자 양성 과정\\AI STUDY\\github\\pandas\\'

data = [[1,np.nan],['A',4.179],['<&>',32000]]
df = pd.DataFrame(data,columns=['col1','col2'])
df=df.rename_axis(columns='index')
print(df)
f = open(address+"Test1-3.html", 'w')
dd = df.to_html()
f.write(dd)
f.close()
print(df.to_html(columns=['col1']))
print(df.to_html(col_space=[100,200]))
print(df.to_html(header=False, index=False))
print(df.to_html(na_rep="결측값"))
time = pd.to_datetime(['16:04:33.500','17:30:00.000'],format='%H:%M:%S.%f')
x = pd.DataFrame({'col':time})
print(x)
def format_func(x):
    return x.strftime('%H:%M')
result = x.to_html(formatters={'col':format_func})
print(result)
print(df.to_html(float_format='{0:.2g}'.format))
print(df.to_html(index_names=False))
print('====='+'left'+'='*20) # 구분을 위해 입력한 값입니다.
print(df.to_html(col_space=[100,100], justify='left'))
print('====='+'right'+'='*20)
print(df.to_html(col_space=[100,100], justify='right'))
print('====='+'center'+'='*20)
print(df.to_html(col_space=[100,100], justify='center'))
print(df.to_html(max_rows=2))
print(df.to_html(max_cols=1))
print(df.to_html(show_dimensions=True))
print(df.to_html(decimal='_'))
print(df.to_html(bold_rows=False))
print(df.to_html(classes='test-making'))
print(df.to_html(escape=False))
print(df.to_html(border=2))
print(df.to_html(table_id='test'))
f = open(address+"Test2-3.html", 'w')
dd = df.to_html(border=2)
f.write(dd)
f.close()

index col1       col2
0        1        NaN
1        A      4.179
2      <&>  32000.000
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>index</th>
      <th>col1</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
    </tr>
    <tr>
      <th>1</th>
      <td>A</td>
    </tr>
    <tr>
      <th>2</th>
      <td>&lt;&amp;&gt;</td>
    </tr>
  </tbody>
</table>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>index</th>
      <th style="min-width: 100px;">col1</th>
      <th style="min-width: 200px;">col2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1</th>
      <td>A</td>
      <td>4.179</td>
    </tr>
    <tr>
      <th>2</th>
      <td>&lt;&amp;&gt;</td>
      <td>32000.000</td>
    </tr>
  </tbody>
</table>
<table border="1" class="dataframe">
  <tbody>
    <tr>
      <td>1</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>A</td>
      <td>4.179</td>
    </tr>
    <tr>
      <td>&lt;&amp;&gt;</td>
      <td>32000.000</td>
    </tr>
  </tbody>
</table>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>index</th>
      <th>col1</th>
      <th>col2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>결측값</td>
    </tr>
    <tr>
      <th>1</th>
      <td>A</td>
      <td>4.179</td>
    </tr>
    <tr>
      <th>2</th>
      <td>&lt;&amp;&gt;</td>
      <td>32000.000</td>
    </tr>
  </tbody>
</table>
                      col
0 1900-01-01 16:04:33.500
1 1900-01-01 17:30:00.000
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>col</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>16:04</td>
    </tr>
    <tr>
      <th>1</th>
      <td>17:30</td>
    </tr>
  </tbody>
</table>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>index</th>
      <th>col1</th>
      <th>col2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1</th>
      <td>A</td>
      <td>4.2</td>
    </tr>
    <tr>
      <th>2</th>
      <td>&lt;&amp;&gt;</td>
      <td>3.2e+04</td>
    </tr>
  </tbody>
</table>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>col1</th>
      <th>col2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1</th>
      <td>A</td>
      <td>4.179</td>
    </tr>
    <tr>
      <th>2</th>
      <td>&lt;&amp;&gt;</td>
      <td>32000.000</td>
    </tr>
  </tbody>
</table>
=====left====================
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: left;">
      <th>index</th>
      <th style="min-width: 100px;">col1</th>
      <th style="min-width: 100px;">col2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1</th>
      <td>A</td>
      <td>4.179</td>
    </tr>
    <tr>
      <th>2</th>
      <td>&lt;&amp;&gt;</td>
      <td>32000.000</td>
    </tr>
  </tbody>
</table>
=====right====================
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>index</th>
      <th style="min-width: 100px;">col1</th>
      <th style="min-width: 100px;">col2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1</th>
      <td>A</td>
      <td>4.179</td>
    </tr>
    <tr>
      <th>2</th>
      <td>&lt;&amp;&gt;</td>
      <td>32000.000</td>
    </tr>
  </tbody>
</table>
=====center====================
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: center;">
      <th>index</th>
      <th style="min-width: 100px;">col1</th>
      <th style="min-width: 100px;">col2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1</th>
      <td>A</td>
      <td>4.179</td>
    </tr>
    <tr>
      <th>2</th>
      <td>&lt;&amp;&gt;</td>
      <td>32000.000</td>
    </tr>
  </tbody>
</table>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>index</th>
      <th>col1</th>
      <th>col2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>&lt;&amp;&gt;</td>
      <td>32000.0</td>
    </tr>
  </tbody>
</table>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>index</th>
      <th>col1</th>
      <th>...</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>...</td>
    </tr>
    <tr>
      <th>1</th>
      <td>A</td>
      <td>...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>&lt;&amp;&gt;</td>
      <td>...</td>
    </tr>
  </tbody>
</table>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>index</th>
      <th>col1</th>
      <th>col2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1</th>
      <td>A</td>
      <td>4.179</td>
    </tr>
    <tr>
      <th>2</th>
      <td>&lt;&amp;&gt;</td>
      <td>32000.000</td>
    </tr>
  </tbody>
</table>
<p>3 rows × 2 columns</p>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>index</th>
      <th>col1</th>
      <th>col2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1</th>
      <td>A</td>
      <td>4_179</td>
    </tr>
    <tr>
      <th>2</th>
      <td>&lt;&amp;&gt;</td>
      <td>32000_000</td>
    </tr>
  </tbody>
</table>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>index</th>
      <th>col1</th>
      <th>col2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>0</td>
      <td>1</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>1</td>
      <td>A</td>
      <td>4.179</td>
    </tr>
    <tr>
      <td>2</td>
      <td>&lt;&amp;&gt;</td>
      <td>32000.000</td>
    </tr>
  </tbody>
</table>
<table border="1" class="dataframe test-making">
  <thead>
    <tr style="text-align: right;">
      <th>index</th>
      <th>col1</th>
      <th>col2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1</th>
      <td>A</td>
      <td>4.179</td>
    </tr>
    <tr>
      <th>2</th>
      <td>&lt;&amp;&gt;</td>
      <td>32000.000</td>
    </tr>
  </tbody>
</table>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>index</th>
      <th>col1</th>
      <th>col2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1</th>
      <td>A</td>
      <td>4.179</td>
    </tr>
    <tr>
      <th>2</th>
      <td><&></td>
      <td>32000.000</td>
    </tr>
  </tbody>
</table>
<table border="2" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>index</th>
      <th>col1</th>
      <th>col2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1</th>
      <td>A</td>
      <td>4.179</td>
    </tr>
    <tr>
      <th>2</th>
      <td>&lt;&amp;&gt;</td>
      <td>32000.000</td>
    </tr>
  </tbody>
</table>
<table border="1" class="dataframe" id="test">
  <thead>
    <tr style="text-align: right;">
      <th>index</th>
      <th>col1</th>
      <th>col2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1</th>
      <td>A</td>
      <td>4.179</td>
    </tr>
    <tr>
      <th>2</th>
      <td>&lt;&amp;&gt;</td>
      <td>32000.000</td>
    </tr>
  </tbody>
</table>

■  string으로 변환(to_string)
* DataFrame.to_string(buf=None, columns=None, col_space=None, header=True, index=True, na_rep='NaN', formatters=None, float_format=None, sparsify=None, index_names=True, justify=None, max_rows=None, max_cols=None, show_dimensions=False, decimal='.', line_width=None, min_rows=None, max_colwidth=None, encoding=None)

to_string 메서드는 데이터 객체를 단순 string 형태로 변형하는 메서드입니다.

- df.to_string(buf=None, columns=None, col_space=None, header=True, index=True, na_rep='NaN', formatters=None, float_format=None, sparsify=None, index_names=True, justify=None, max_rows=None, max_cols=None, show_dimensions=False, decimal='.', line_width=None, min_rows=None, max_colwidth=None, encoding=None)
buf : 저장할 버퍼 입니다. None이면 문자열로 출력됩니다.
columns : 출력할 열을 지정합니다.
col_space : 열 너비를 지정합니다. .
header / index : 열/행 레이블의 출력 여부 입니다. False이면 출력하지 않습니다.
리스트 형태로 입력하여 레이블명의 변경이 가능합니다.
na_rep : 결측값의 표현 방식 입니다.
formatters : 포매터 함수를 통해 값의 포맷을 설정합니다. .format() 메서드도 사용 가능합니다.
float_format : 소수점 단위 자리수를 지정합니다. 기본은 마침표( . ) 입니다.
※ formatters / float_format 의 사용법은 19-07 html형태 변환to_html 에 자세히 설명 되어있으므로 참고 바랍니다.
sparsify : 각 행의 모든 다중 인덱스 키를 인쇄하려면 계층적 인덱스가 있는 DataFrame에 대해 False로 설정합니다.
index_names : 인덱스명을 출력할지를 정합니다.
justify : 정렬 방식을 지정합니다. {left / right / center / justify / justify-all / start / end / inherit / match-parent / initial / unset}
maxrows : 최대 출력할 줄 수를 지정합니다. 초과되는 줄은 ( ... )형태로 축약됩니다.
maxcols : 최대 출력할 열 수를 지정합니다. 초과되는 줄은 ( ... )형태로 축약됩니다.
show_dimensions : 출력된 html 객체 아래에 데이터 객체의 차원을 출력합니다.
decimal : 1000단위 구분기호로 인식되는 문자를 지정합니다.
linewidth : 문자로 줄바꿈할 너비 입니다.
minrow : maxrows로인해 잘린 표현을 표시할 수 입니다.
max_colwidth : 각 열을 문자열로 자르기 위한 최대 너비입니다. 기본값은 무제한 입니다.
encoding : 인코딩을 지정합니다.

■  numpy로 변환 (values)
* DataFrame.values
DataFrame.to_numpy를 사용하는것을 추천합니다.
DataFrame 요소를 Numpy 형태(numpy.ndarray)로 반환합니다. 레이블은 삭제됩니다.
- df.values

■  dict에서 변환 (from_dict)
* DataFrame.DataFrame.from_dict(data, orient='columns', dtype=None, columns=None)
from_dict메서드는 dict객체로부터 DataFrame 객체로 변환하는 메서드입니다.
- df.from_dict(data, orient='columns', dtype=None, columns=None)
data : dict 형태의 데이터 입니다.
orient : {index / columns / tight} 변환 방식입니다. index은 행을 키값으로 지정, columns는 열을 키값으로 지정, tight는 키값으로 [index / columns / data / index_names / columns_names] 를 가집니다. orient인수의 기본값은 'columns'로 키값으로 열 이름을 사용하게 됩니다.
dtype : 데이터의 type을 강제로 지정할 수 있습니다.
columns : index인수를 사용할 경우 columns인수를 통해 열 이름을 지정할 수 있습니다.

In [ ]:
data = [[1,np.nan],['A',4.179],['<&>',32000]]
df = pd.DataFrame(data,columns=['col1','col2'])
df=df.rename_axis(columns='index')
print(df)
print("**************************to_string() ****************\n",df.to_string())
print(type(df))
print(type(df.to_string()))
print(df.to_string(columns=['col2'])) # col2만 출력
print(df.to_string(col_space=[10,20]))
print(df.to_string(header=['val1','val2']))
print(df.to_string(index=False))
print(df.to_string(na_rep='결측'))
# index_names를 설정함으로서 인덱스명의 출력 여부를 정할 수 있습니다. 기본값은 True입니다.
#```{.python print(df.to_string(index_names=False))
    #col1 col2 # 인덱스명이 출력되지 않음 0 1 NaN 1 A 4.179 2 <&> 32000.000
print(df.to_string(justify='left'))
print(df.to_string(max_rows=2))
print(df.to_string(max_cols=1))
print(df.to_string(show_dimensions=True))
print(df.to_string(decimal='_'))
print(df.to_string(line_width=2))
print(df.to_string(max_colwidth=5))

col1 = [1, 2, 3, 4]
col2 = ['one', 'two', 'three', 'four']
col3 = [1.5, 2.5, 3.5, 4.5]
col4 = [True, False, False, True]
index = ['row1','row2','row3','row4']
df = pd.DataFrame(index=index, data={"col1": col1, "col2": col2, "col3": col3, "col4": col4})
print(df)
result = df.values
print(result)
data = {'col1':[1,3],'col2':[2,4]}
df = pd.DataFrame.from_dict(data=data, orient='columns')
print(df)
data = {'row1':[1,2],'row2':[3,4]}
df = pd.DataFrame.from_dict(data=data, orient='index')
print(df)
df = pd.DataFrame.from_dict(data=data, orient='index', columns=['col1','col2'])
print(df)
df = pd.DataFrame.from_dict(data=data, orient='index', columns=['col1','col2'],dtype='float')
print(df)

data =  {'index'        : [('idx1','row1'),('idx1','row2')], # 인덱스 이름 설정, 멀티 인덱스 가능
         'columns'      : [('col1','val1'),('col2','val2')], # 열 이름 설정, 멀티 컬럼 가능
         'data'         : [[1,2],[3,4]], # 데이터 값 설정
         'index_names'  : ['I1','I2'], # 인덱스명 설정
         'column_names' : ['C1','C2']} # 컬럼명 설정
df = pd.DataFrame.from_dict(data=data, orient='tight')
print(df)

index col1       col2
0        1        NaN
1        A      4.179
2      <&>  32000.000
**************************to_string() ****************
 index col1       col2
0        1        NaN
1        A      4.179
2      <&>  32000.000
<class 'pandas.DataFrame'>
<class 'str'>
index       col2
0            NaN
1          4.179
2      32000.000
index       col1                 col2
0              1                  NaN
1              A                4.179
2            <&>            32000.000
index val1       val2
0        1        NaN
1        A      4.179
2      <&>  32000.000
col1      col2
   1       NaN
   A     4.179
 <&> 32000.000
index col1       col2
0        1         결측
1        A      4.179
2      <&>  32000.000
index col1  col2
0        1        NaN
1        A      4.179
2      <&>  32000.000
index col1     col2
0        1      NaN
..     ...      ...
2      <&>  32000.0
index col1  ...
0        1  ...
1        A  ...
2      <&>  ...
index col1       col2
0        1        NaN
1        A      4.179
2      <&>  32000.000

[3 rows x 2 columns]
index col1       col2
0        1        NaN
1        A      4_179
2      <&>  32000_000
index col1  \
0        1
1        A
2      <&>

index       col2
0            NaN
1          4.179
2      32000.000
index col1  col2
0        1   NaN
1        A  4...
2      <&>  3...
      col1   col2  col3   col4
row1     1    one   1.5   True
row2     2    two   2.5  False
row3     3  three   3.5  False
row4     4   four   4.5   True
[[1 'one' 1.5 True]
 [2 'two' 2.5 False]
 [3 'three' 3.5 False]
 [4 'four' 4.5 True]]
   col1  col2
0     1     2
1     3     4
      0  1
row1  1  2
row2  3  4
      col1  col2
row1     1     2
row2     3     4
      col1  col2
row1   1.0   2.0
row2   3.0   4.0
C1        col1 col2
C2        val1 val2
I1   I2
idx1 row1    1    2
     row2    3    4